DELETE http://localhost:3001/api/persons/63da7f8ac0462f79b79bed29

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Rosario",
    "number": "67999033455"
}

###
GET http://localhost:3001/api/persons/63da7f8ac0462f79b79bed29

###
PUT http://localhost:3001/api/persons/63da7baa065d2cd1586e6243
Content-Type: application/json

{
    "number": "67999033455"
}